#!/bin/bash
mvn clean package
docker build -f src/main/docker/Dockerfile  -t localhost:5000/mspocws .
docker push localhost:5000/mspocws

#verificamos que la aplicacion ya exista para que no la parche al primer despliegue
EXISTS=false
if kubectl get deployments -n=cima-dev | grep -q mspocws-app; then
	 EXISTS=true
fi
kubectl apply -f src/main/docker/kubernetes/

#si existe la aplicacion la parcha y se actualiza
if [ "$EXISTS" == true ]; then
	 kubectl patch deployment mspocws-app -p '{"spec":{"template":{"metadata":{"labels": { "buildate" : "'$(date '+%d-%m-%Y_%H.%M.%S.%3N')'", "version" : "latest"}}}}}' -n=cima-dev
fi

